### ISSUE TITLE
Is django-selenium still usefull?

### ISSUE THREAD

**Issue by guettli** [dragoon/django-selenium#27]
Please update the docs:

https://django-selenium.readthedocs.org/en/latest/#django-1-4-note

Is this project still useful since django has selenium support?

Please tell us the features which this project has and which are missing from the django built in selenium support.

Thank you.

**Comment by guettli** [comment]
I guess current django versions don't need a third party app (except selenium itself).
Here are the django docs: https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.LiveServerTestCase

**Comment by MiltosD** [comment]
Well, it does not work with Django 1.10. Any chance to add such support? Django is already in v.2.0

**Comment by dragoon** [comment]
@MiltosD, as far as I know, Django > 1.5 has built-in selenium support, why do you think you need this library?

**Comment by MiltosD** [comment]
@dragoon Well, it's being used across the existing code to be upgraded, so I was just wondering.

**Comment by guettli** [comment]
My conclusion: This project is useful for older releases of django. Closing this issue. ok?
