### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by guettli** [dragoon/django-selenium#29]
Is this project still alive?

The docs look a bit outdated, since south has gone since several django releases:

https://django-selenium.readthedocs.org/en/latest/#south

If you have no time, that's ok. Please be upright and tell us the state of the project.

Thank you.

**Comment by guettli** [comment]
I guess current django versions don't need a third party app (except selenium itself).
Here are the django docs: https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.LiveServerTestCase

**Comment by dragoon** [comment]
Hello Thomas, that's correct, you don't need 3rd-party app anymore, that's why there is not much development in here.

**Comment by guettli** [comment]
You know it. I know it, but new users don't. It would be polite to publish above on the start page of this github project.
